version: '3.1'

services:

  letsencrypt-nginx:
    container_name: 'letsencrypt-nginx'
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ${DOCKER_VOLUME}/letsencrypt/conf:/etc/letsencrypt
      - ./html:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - docker-network

networks:
  docker-network:
    driver: bridge