version: '3'

services:
    sabnzbd:
        container_name: sabnzbd
        image: linuxserver/sabnzbd
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - /home/dougie/mywd1/Downloads:/Downloads
        - ${DOCKER_VOLUME}/sabnzbd:/config
        ports:
        - 8888:8888
        - 9090:9090
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        depends_on: 
        - sabnzbd
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - /home/dougie/mywd1/Downloads:/Downloads
        - ${DOCKER_VOLUME}/radarr:/config
        ports:
        - 7878:7878
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        depends_on: 
        - sabnzbd
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - /home/dougie/mywd1/Downloads:/Downloads
        - ${DOCKER_VOLUME}/sonarr:/config
        ports:
        - 8989:8989
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    ombi:
        container_name: ombi
        image: linuxserver/ombi
        restart: unless-stopped
        volumes:
        - ${DOCKER_VOLUME}/ombi:/config
        ports:
        - 3579:3579
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    organizr:
        container_name: organizr
        image: lsiocommunity/organizr
        restart: unless-stopped
        ports:
        - 8899:8899
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - dougie-fresh

    watchtower:
        container_name: watchtower
        image: v2tec/watchtower
        restart: unless-stopped
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
          #      - ${DOCKER_VOLUME}/watchtower/config.json:/config.json

    production-nginx-container:
        container_name: 'dougie-fresh-nginx-container'
        image: nginx:alpine
        restart: unless-stopped
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - ./letsencrypt-nginx/dougie-fresh-nginx.conf:/etc/nginx/conf.d/default.conf
        - ./letsencrypt-nginx/live:/usr/share/nginx/html
        - ./letsencrypt-nginx/dh-param/dhparam-2048.pem:/etc/ssl/certs/dhparam-2048.pem
        - /home/dougie/mywd1/docker-volumes/letsencrypt/etc/letsencrypt/live/dougie-fresh.xyz/fullchain.pem:/etc/letsencrypt/live/dougie-fresh.xyz/fullchain.pem
        - /home/dougie/mywd1/docker-volumes/letsencrypt/etc/letsencrypt/live/dougie-fresh.xyz/privkey.pem:/etc/letsencrypt/live/dougie-fresh.xyz/privkey.pem
        networks:
            - dougie-fresh
    
    #network_mode: "host"

networks:
    dougie-fresh:
        driver: bridge
