version: '3'

services:
    sabnzbd:
        container_name: sabnzbd
        image: linuxserver/sabnzbd
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - /home/dougie/Downloads:/Downloads
        - ${DOCKER_VOLUME}/sabnzbd:/config
        ports:
        - 8888:8080
        - 9090:9090
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - htpc

    radarr:
        container_name: radarr
        image: linuxserver/radarr
        depends_on: 
        - sabnzbd
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mywd1:${MEDIA_HOME}/mywd1
        - ${MEDIA_HOME}/myrepo:${MEDIA_HOME}/myrepo
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - /home/dougie/Downloads:/Downloads
        - ${DOCKER_VOLUME}/radarr:/config
        ports:
        - 7878:7878
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - htpc

    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        depends_on: 
        - sabnzbd
        restart: unless-stopped
        volumes:
        - ${MEDIA_HOME}/mytoshiba1:${MEDIA_HOME}/mytoshiba1
        - ${MEDIA_HOME}/toshiba5tb:${MEDIA_HOME}/toshiba5tb
        - ${BUFFALO_HOME}/media:${BUFFALO_HOME}/media
        - /home/dougie/Downloads:/Downloads
        - ${DOCKER_VOLUME}/sonarr:/config
        ports:
        - 8989:8989
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - htpc

    ombi:
        container_name: ombi
        image: linuxserver/ombi
        restart: unless-stopped
        volumes:
        - ${DOCKER_VOLUME}/ombi:/config
        ports:
        - 3579:3579
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
        networks:
            - htpc

    organizr:
        container_name: organizr
        image: lsiocommunity/organizr
        restart: unless-stopped
        ports:
        - 8899:80
        environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}

    watchtower:
        container_name: watchtower
        image: v2tec/watchtower
        restart: unless-stopped
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
          #      - ${DOCKER_VOLUME}/watchtower/config.json:/config.json

networks:
    htpc:
        driver: bridge
